name: Run Smoke - Api-Utils Update
on:
  pull_request:
    types: [ labeled ]
    branches:
      - main

env:
  JENKINS_FOLDER_PATH: ${{ github.event.repository.name }}
  JENKINS_CREDENTIALS: ${{ secrets.JENKINS_USER_TOKEN_ENCR }}
  JENKINS_URL: "https://automation.qateam.bamgrid.com/jenkins"
  JENKINS_PARAMS: |
    {
      "branch":"${{ github.head_ref }}"
    }

jobs:
  ios_handset_smoke_tests:
    outputs:
      handset_status_output: ${{ steps.build_ios_handset_smoke.outputs.result }}
      handset_build_url_output: ${{ steps.build_ios_handset_smoke.outputs.build_url }}
    if: ${{ github.event.label.name == 'disney api utils update' }}
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: qait/qait-github-actions
          token: ${{ secrets.GH_TOKEN }}

      - name: Run iOS Handset Smoke Tests
        id: build_ios_handset_smoke
        uses: ./action-build-job
        with:
          url: ${{ env.JENKINS_URL }}
          api_credentials: ${{ env.JENKINS_CREDENTIALS }}
          folder_path: ${{ env.JENKINS_FOLDER_PATH }}
          job_name: DisneyPlus-iOS-Api-Utils-Run
          parameters: ${{ env.JENKINS_PARAMS }}
          start_timeout: 60
          build_timeout: 1500
          interval: 30

  tv_os_smoke_tests:
    outputs:
      tv_os_status_output: ${{ steps.build_tv_os_smoke.outputs.result }}
      tv_os_build_url_output: ${{ steps.build_tv_os_smoke.outputs.build_url }}
    if: ${{ github.event.label.name == 'disney api utils update' }}
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: qait/qait-github-actions
          token: ${{ secrets.GH_TOKEN }}

      - name: Run tvOS Smoke Tests
        id: build_tv_os_smoke
        uses: ./action-build-job
        with:
          url: ${{ env.JENKINS_URL }}
          api_credentials: ${{ env.JENKINS_CREDENTIALS }}
          folder_path: ${{ env.JENKINS_FOLDER_PATH }}
          job_name: DisneyPlus-tvOS-Api-Utils-Run
          parameters: ${{ env.JENKINS_PARAMS }}
          start_timeout: 60
          build_timeout: 1500
          interval: 30

  pr_comment_failure:
    needs: [ios_handset_smoke_tests, tv_os_smoke_tests]
    runs-on: self-hosted
    if: always()
    steps:
      - name: Comment on Results
        id: pr_comment_fail_notifier
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            🚨 Api Smoke tests have been run.  
            **Handset Status:** ${{ needs.ios_handset_smoke_tests.outputs.handset_status_output }}
            **Handset Job Url:** ${{ needs.ios_handset_smoke_tests.outputs.handset_build_url_output }}
            
            **tvOS Status:** ${{ needs.tv_os_smoke_tests.outputs.tv_os_status_output }}
            **tvOS Job Url:** ${{ needs.tv_os_smoke_tests.outputs.tv_os_handset_build_url_output }} 
